-- Migration 002: day plans + reviews

-- Structured daily agenda generated by debrief
CREATE TABLE IF NOT EXISTS day_plans (
  id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  plan_date   DATE NOT NULL UNIQUE,
  wake_time   TEXT,                 -- HH:MM, e.g. "07:00"
  work_start  TEXT,                 -- HH:MM, e.g. "07:30"
  schedule    JSONB NOT NULL DEFAULT '[]',  -- [{time,title,type,duration_min}]
  overflow    JSONB NOT NULL DEFAULT '[]',  -- [string] task titles that didn't fit
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Review sessions (weekly / monthly / quarterly)
CREATE TABLE IF NOT EXISTS reviews (
  id           UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  review_type  TEXT NOT NULL CHECK (review_type IN ('weekly','monthly','quarterly')),
  period_start DATE NOT NULL,
  period_end   DATE NOT NULL,
  content      JSONB NOT NULL DEFAULT '{}',
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS day_plans_plan_date_idx ON day_plans(plan_date);
CREATE INDEX IF NOT EXISTS reviews_period_start_idx ON reviews(period_start DESC);
