-- Add 2-minute start action columns to day_plans.
-- These are generated by Claude during the daily debrief and stored for display in the dashboard.
ALTER TABLE day_plans ADD COLUMN IF NOT EXISTS mit_start_action TEXT;
ALTER TABLE day_plans ADD COLUMN IF NOT EXISTS p1_start_action  TEXT;
ALTER TABLE day_plans ADD COLUMN IF NOT EXISTS p2_start_action  TEXT;
